apiVersion: "v1"
kind: "Template"
metadata:
  name: "thermostat-mongodb-online-starter"
objects:
###################
## IMAGE STREAMS ##
###################
#### MONGO #####
# mongodb image
- apiVersion: "v1"
  kind: "ImageStream"
  metadata:
    name: "thermostat-mongodb-32-rhel7"
    labels:
      app-group: "thermostat-online-starter"
  spec:
    dockerImageRepository: "registry.access.redhat.com/rhscl/mongodb-32-rhel7"
#################
## CONFIG MAPS ##
#################
- apiVersion: "v1"
  kind: "ConfigMap"
  metadata:
    name: "thermostat-mongodb-config"
    labels:
      app-group: "thermostat-online-starter"
  data:
    mongod.conf: |+
      ##
      ## For list of options visit:
      ## https://docs.mongodb.org/manual/reference/configuration-options/
      ##

      # systemLog Options - How to do logging
      systemLog:
        # Runs the mongod in a quiet mode that attempts to limit the amount of output
        quiet: true


      # net Options - Network interfaces settings
      net:
        # Specify port number (27017 by default)
        port: 27017


      # storage Options - How and Where to store data
      storage:
        # Directory for datafiles (defaults to /data/db/)
        dbPath: /var/lib/mongodb/data
        # Limit WiredTiger cache size to avoid consuming too much memory
        wiredTiger:
          engineConfig:
             configString : cache_size=96M


      # replication Options - Configures replication
      replication:
        # Specifies a maximum size in megabytes for the replication operation log (i.e. the oplog,
        # 5% of disk space by default)
        oplogSizeMB: 64

########################
## DEPLOYMENT CONFIGS ##
########################
# mongodb dc
- apiVersion: "v1"
  kind: "DeploymentConfig"
  metadata:
    name: "thermostat-mongodb-dc"
    labels:
      app: "thermostat-mongodb-app"
      app-group: "thermostat-online-starter"
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
  spec:
    triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        containerNames:
        - thermostat-mongodb-container
        from:
          kind: "ImageStreamTag"
          name: "thermostat-mongodb-32-rhel7:latest"
    template:
      metadata:
        labels:
          app: "thermostat-mongodb-app"
          app-group: "thermostat-online-starter"
      spec:
        containers:
        - name: "thermostat-mongodb-container"
          image: "thermostat-mongodb-32-rhel7:latest"
          imagePullPolicy: "Always"
          env:
          - name: "MONGODB_ADMIN_PASSWORD"
            value: "arst"
          - name: "MONGODB_DATABASE"
            value: "thermostat"
          - name: "MONGODB_PASSWORD"
            value: "mongo"
          - name: "MONGODB_USER"
            value: "mongo"
          # OSO Starter: Set container memory limit to 1/4 of our total quota
          resources:
            limits:
              memory: "256Mi"
          volumeMounts:
          - mountPath: "/var/lib/mongodb/data"
            name: "thermostat-mongo-storage"
            # OSO Starter: Override mongod.conf to support cache sizes under 1GiB
          - mountPath: "/etc/mongod.conf"
            name: "mongodb-config-volume"
            # Workaround SELinux labelling bug for single file mounts, as suggested in
            # https://bugzilla.redhat.com/show_bug.cgi?id=1481617#c1
            subPath: "..data/mongod.conf"
        volumes:
        - name: "thermostat-mongo-storage"
          emptyDir: {}
        - name: "mongodb-config-volume"
          configMap:
            name: "thermostat-mongodb-config"
            defaultMode: 0660
    selector:
      app: "thermostat-mongodb-app"
    replicas: 1
    strategy:
      type: "Recreate"
##############
## SERVICES ##
##############
# mongo service
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "thermostat-mongodb-svc"
    labels:
      app: "thermostat-mongodb-app"
      app-group: "thermostat-online-starter"
  spec:
    selector:
      app: "thermostat-mongodb-app"
    ports:
    - name: 27017-tcp
      protocol: TCP
      port: 27017
      targetPort: 27017
